### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by mcturco** [asyncapi/brand#14]
@alequetzalli mentioned that it would be great to include a README file in this repo so that we can better introduce the repo's purpose to the community & provide instructions on how to contribute. Any ideas for the structure of this file are welcome!

**Comment by alequetzalli** [comment]
Here are some ideas, in case they help:

- Start the README by welcoming them to the project, introducing them to the contribution guidelines, and requesting they read the CoC before they submit any contributions/get involved
- Detail what kind of design contributions are needed:
    - Font changes? 
    - Can individuals pick up any of your GH issues in your Design board? Can a contributor simply introduce themselves and create a PR for one of your issues?
    - UI components? 
    - Feedback?
- Detail your current proposed brand roadmap changes so that the community can see at a glance what is coming up and how they can jump in to help you or to propose improvements to your plan.
- Add a section encouraging folks to join your Slack design channel and GH Discussion threads on Design.

**Comment by mcturco** [comment]
@alequetzalli thank you so much for this! It definitely helps a ton!! <3
